---
driver:
  name: ec2
  aws_ssh_key_id: default
  region: eu-west-1
  availability_zone: a
  subnet_id: subnet-edf72d8a
  instance_type: t2.micro
  image_id: ami-f1978897
  security_group_ids: sg-1b7c8d63
  retrayable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: ~/aws/keys/default.pem

platforms:
  - name: rhel-7

suites:
  - name: default
    run_list:
      - recipe[learn_chef_httpd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
